stage: "STANDARD"
in_channels: 14
out_channels: 6
num_levels: 32
num_nodes: 2562

paths:
  zarr_store: "/scratch4/NAGAPE/epic/Wei.Huang/src/starviewergraphcast/data/gfs_icosahedral_m4.zarr"
  data_dir: "/scratch4/NAGAPE/epic/Wei.Huang/src/starviewergraphcast/data/gfs_icosahedral_m4.zarr"
  graph_dir: "/scratch4/NAGAPE/epic/Wei.Huang/src/starviewergraphcast/graph/starviewergraphcast-grid"
  grid_ref: "/scratch4/NAGAPE/epic/Wei.Huang/src/starviewergraphcast/data/starviewergraphcast-grid/global_icosahedral_m4.20220101.t00z.1p00.f000.nc"

model_params:
  hierarchy_levels: [4, 3, 2, 1, 0]
  history_steps: 2
  rollout_steps: 6
  latent_dim: 512          # Scaled up from 256 to increase model capacity
  processor_layers: 16
  learning_rate: 1.0e-04

training_params:
  batch_size: 2            # Adjusted for higher GPU memory usage
  max_epochs: 25
  num_workers: 4
  gradient_clip_val: 0.5
  precision: "bf16-mixed"

# Balanced Normalized MSE Weights
loss_weights:
  weight_P: 1.0
  weight_Q: 1.0
  weight_T: 1.0
  weight_U: 2.5            # Kinetic energy loss weighting
  weight_V: 2.5
  weight_W: 1.0
